### ISSUE TITLE
Attribute für Autos hinzufügen

### ISSUE THREAD

**Issue by Thxrsty** [Timplayer/SWSYSPRO-Projekt#185]
Links steht der name des atrributs rechts was es bedeuten soll

**Sortieren nach (SortOption):**

lowestPrice (Niedrigster Preis zuerst)
highestPrice (Höchster Preis zuerst)
electricFirst (Elektrische Fahrzeuge zuerst)

**Fahrzeugkategorie (VehicleCategory):**

limousine (Limousine)
suv (SUV)
coupe (Coupé)
cabriolet (Cabriolet)
kombi (Kombi)
electricVehicle (Elektrisches Fahrzeug)
luxuryVehicle (Luxus Fahrzeug)
specialVehicle (Spezial Fahrzeug)

**Getriebe (Transmission):**

automatic (Automatik)
manual (Manuell)

**Antrieb (DriveType):**

frontWheel (Frontantrieb)
rearWheel (Heckantrieb)
allWheel (Allradantrieb)

**Anzahl Sitze (SeatCount):**

2+ (2+)
4+ (4+)
5+ (5+)
7+ (7+)

**Alter des Fahrers (DriverAge):**

18+ (18+)
21+ (21+)
23+ (23+)
25+ (25+)

ein Auto sollte auch einen Tagespreis haben?

price

**Comment by Timplayer** [comment]
These attributes should be added to the vehicleType #187 table.
