### ISSUE TITLE
Check if image post method body is sensible

### ISSUE THREAD

**Issue by AlphaLEXray** [Timplayer/SWSYSPRO-Projekt#75]
Currently the POST method to create images has a multipart form as body.

The question is now, if it is sensible to replace the multipart form with JSON where the file is encoded as bytes.

**Comment by AlphaLEXray** [comment]
Sending a file as JSON breaks the testing framework. Probably not a good idea.

**Comment by Niko4u5** [comment]
We could have an Endpoint like ```/api/images```.
we Post an image directly to it with content type ```image/*```
you recive some json with the url of the saved image (```/api/images/{someId}```)
now you can include this url in other requests when adding images to things

**Comment by AlphaLEXray** [comment]
That is a good approach and the way it is currently implemented.

The Problem is how the images are connected with other entities (i.e. vehicles). The connection is realized with another table, which needs the ImageID and the Id of the other entity. Thus when creating an instance of the entity the images (which are uploaded via a separate request) need to be linked to this instance via the "connection table".

**Comment by Niko4u5** [comment]
cant you include a list of images in the creation request for the entity?

**Comment by AlphaLEXray** [comment]
Yes, but then the client would need to know the id of the images either beforehand or it would need to receive a list of ids for the images linked to this instance of the entity.

At least in the way I am currently envisioning it.

**Comment by Niko4u5** [comment]
the client uplads an image gets the image id.
then it creats the entity with that image.

or am i missing something

**Comment by AlphaLEXray** [comment]
The image id is currently not returned. That will be addressed.
